#!/bin/bash

# XPRA
# x11docker --xpra --gpu --clipboard --lang="hu_HU" --home="" --sudouser --dbus --cap-default -- -v /eda:/eda -- centos-eda $*

# HOST DISPLAY
x11docker -q --hostdisplay --gpu --clipboard --lang="hu_HU" --home="" --sudouser --dbus --cap-default -i -- -v /eda:/eda -- centos-eda $*
