#!/bin/bash

export CDS_LIC_FILE=5280@10.0.30.1
export MGLS_LICENSE_FILE=1717@10.0.30.1
export LM_LICENSE_FILE=5280@10.0.30.1:1717@10.0.30.1
export OA_UNSUPPORTED_PLAT=linux_rhel60

source /eda/cadence/2018-19/scripts/IC_6.1.8.000_RHELx86.sh

